name = "AerosolRegistry"
uuid = "5c641185-443a-44c3-92f5-a6d6de0f7521"
repo = "git@github.com:mdp-aerosol-group/registry.git"
description = "Petters Aerosol Group Registry"

[packages]
050a7be8-18f9-52d6-bdba-0a194485d082 = { name = "DifferentialMobilityAnalyzers", path = "D/DifferentialMobilityAnalyzers" }
3395841d-9331-4dd3-aff4-323d07427c2c = { name = "UnipolarCharging", path = "U/UnipolarCharging" }
